# Generated by Django 5.0.2 on 2024-04-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_uploadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
